name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" >> .env
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      # Création du fichier vercel.json avec les bons paramètres
      - name: Create vercel.json with proper configuration
        run: |
          cat > vercel.json << 'EOL'
          {
            "version": 2,
            "buildCommand": "npm run build",
            "outputDirectory": "dist",
            "routes": [
              { "handle": "filesystem" },
              { "src": "/assets/(.*)", "headers": { "cache-control": "public, max-age=31536000, immutable" } },
              { "src": "/(.*\\.(js|css|svg|png|jpg|jpeg|gif|webp|ico))", "headers": { "cache-control": "public, max-age=31536000" } },
              { "src": "/(.*)", "dest": "/index.html" }
            ],
            "github": {
              "enabled": false
            }
          }
          EOL
      
      # Déploiement de prévisualisation pour les PRs avec nom SEO-friendly
      - name: Deploy to Vercel Preview
        if: github.event_name == 'pull_request'
        run: |
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }} --name allan-lannoy-portfolio > vercel_output.txt
          PREVIEW_URL=$(cat vercel_output.txt)
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
          echo "::notice title=Preview Deployment::Your app is deployed at $PREVIEW_URL"
      
      # Déploiement en production avec nom SEO-friendly
      - name: Deploy to Vercel Production
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        run: |
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }} --name allan-lannoy-portfolio > vercel_output.txt
          PRODUCTION_URL=$(cat vercel_output.txt)
          echo "PRODUCTION_URL=$PRODUCTION_URL" >> $GITHUB_ENV
          echo "::notice title=Production Deployment::Your app is deployed at $PRODUCTION_URL"