name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" >> .env
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      # Créer fichier de configuration vercel.json si nécessaire
      - name: Ensure vercel.json exists
        run: |
          if [ ! -f "vercel.json" ]; then
            echo '{
              "version": 2,
              "builds": [
                { "src": "package.json", "use": "@vercel/static-build", "config": { "buildCommand": "npm run build", "outputDirectory": "dist" } }
              ],
              "routes": [
                { "src": "/(.*)", "dest": "/index.html" }
              ],
              "github": {
                "enabled": false
              }
            }' > vercel.json
          fi
      
      # Déploiement de prévisualisation pour les PRs
      - name: Deploy to Vercel Preview
        if: github.event_name == 'pull_request'
        run: |
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }} --name portfolio-allan > vercel_output.txt
          PREVIEW_URL=$(cat vercel_output.txt)
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
          echo "::notice title=Preview Deployment::Your app is deployed at $PREVIEW_URL"
      
      # Déploiement en production pour master
      - name: Deploy to Vercel Production
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        run: |
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes --scope ${{ secrets.VERCEL_ORG_ID }} --name portfolio-allan > vercel_output.txt
          PRODUCTION_URL=$(cat vercel_output.txt)
          echo "PRODUCTION_URL=$PRODUCTION_URL" >> $GITHUB_ENV
          echo "::notice title=Production Deployment::Your app is deployed at $PRODUCTION_URL"