name: Docker Build & Push

on:
  workflow_run:
    workflows: ["Verify Linter"]
    types:
      - completed
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      
      - name: Create .env file from secrets
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" >> .env
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}
            VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
            VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
            
      - name: Echo image URL
        if: github.event_name != 'pull_request'
        run: |
          echo "::notice::Image built and pushed: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}"
          echo "::notice::Image URL: https://github.com/${{ github.repository }}/pkgs/container/${{ github.event.repository.name }}"

  deploy-preview:
    name: Deploy Preview Environment
    if: github.event_name == 'pull_request'
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
        - name: Echo preview deployment info
          run: |
            echo "::notice::PR preview deployment would go here"
            # Pour workflow_run, ces valeurs ne sont pas disponibles directement
            echo "::notice::Triggered by workflow: ${{ github.event.workflow_run.workflow_id }}"